apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.core.name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version}}"
  annotations:
    {{- if .Values.controller.podAnnotations }}
    {{- with .Values.controller.podAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
data:
  APPPATH: {{ .Values.core.config.APPPATH | quote }}
  {{- if .Values.core.config.slack.enabled }}
  {{- with .Values.core.config.slack }}
  SLACK__EMOJI: {{ .SLACK_EMOJI | quote | indent 4}}
  SLACK__DEPLOY__CHANNEL: {{ .SLACK_DEPLOY_CHANNEL | quote }}
  SLACK__DEPLOY__USERNAME: {{ .SLACK_DEPLOY_USERNAME | quote }}
  SLACK__INTERNAL__CHANNEL: {{ .SLACK_INTERNAL_CHANNEL | quote }}
  SLACK__INTERNAL__USERNAME: {{ .SLACK_INTERNAL_USERNAME | indent 4}}
  SLACK__USER__CHANNEL: {{ .SLACK_USER_CHANNEL | quote | indent 4}}
  SLACK__USER__USERNAME: {{ .SLACK_USER_USERNAME | quote }}
  {{- end }}
  {{- end }}
  SPARK__NAMESPACE: {{ index .Values "spark-operator" "sparkJobNamespace" | default .Release.Namespace | quote}}
  SPARK__VOLUME: {{ .Values.core.config.volume.volumeClaimName }}
  SPARK__FILE_URL: {{ printf "http://%s/internal/pyfile" .Values.core.name }}
  SPARK__CALLBACK_URL: {{ printf "http://%s%s" .Values.core.name .Values.core.config.spark.CALLBACK_URL }}
  SPARK__IMAGE: {{ .Values.core.config.spark.SPARK_IMAGE }}
  {{- if .Values.core.config.spark.SPARK_IMAGEPULLSECRETS }}
  SPARK__IMAGEPULLSECRETS: {{ .Values.core.config.spark.SPARK_IMAGEPULLSECRETS }}
  {{- end }}
  {{- if .Values.core.auth.discoveryUrl }}
  DISCOVERY_URL: {{ .Values.core.auth.discoveryUrl }}
  {{- end }}
  {{- if .Values.core.auth.callbackUrl }}
  {{- if .Values.ingress.proxy }}
  CALLBACK_URL: {{ printf "https://%s%s" .Values.ingress.proxy .Values.core.auth.callbackUrl }}
  {{ else }}
  CALLBACK_URL: {{ printf "https://%s%s" .Values.ingress.host .Values.core.auth.callbackUrl }}
  {{- end }}
  {{- end }}