{{- if .Values.help.createservice }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.help.name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version}}"
  annotations:
    {{- if .Values.avp_path }}
    avp_path: {{ .Values.avp_path }}
    {{- end }}
    {{- if .Values.controller.podAnnotations }}
    {{- with .Values.controller.podAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
type: Opaque
{{- if .Values.common.secrets.SLACKHOOK }}
{{- if not .Values.base64 }}
stringData:
  SLACKHOOK: {{ .Values.common.secrets.SLACKHOOK  }}
{{ else }}
data:
  SLACKHOOK: {{ .Values.common.secrets.SLACKHOOK | b64enc }}
{{- end }}
{{- end }}
{{- end }}
