kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.nodepy.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.nodepy.name }}
    tier: {{ .Values.nodepy.tier }}
    version: {{ .Values.nodepy.version }}
spec:
  replicas: {{ .Values.nodepy.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.nodepy.name }}
      tier: {{ .Values.nodepy.tier }}
  template:
    metadata:
      name: {{ .Values.nodepy.name }}
      labels:
        app: {{ .Values.nodepy.name }}
        tier: {{ .Values.nodepy.tier }}
    spec:
      containers:
        - name: {{ .Values.nodepy.name }}
          image: {{ .Values.nodepy.image }}
          envFrom:
            - configMapRef:
                name: {{ .Values.common.config.configmapref }}
            - secretRef:
                name: {{ .Values.common.secrets.secretmapref }}
            - configMapRef:
                name: {{ .Values.nodepy.configmapref }}
          resources: {}
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: false
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "15"]
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
