apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.core.name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version}}"
type: Opaque
data:
  SESSION__NAME: {{ .Values.core.secrets.SESSION_NAME | b64enc }}
  SESSION__SECRET: {{ .Values.core.secrets.SESSION_SECRET | b64enc }}
  {{- if .Values.mongodb.createservice }}
  MONGO__URL: {{ printf "mongodb://%s:%s@%s-mongodb:27017/%s" .Values.mongodb.auth.username .Values.mongodb.auth.password .Release.Name .Values.mongodb.auth.database | b64enc }}
  {{- else if .Values.core.secrets.MONGO_URL }}
  MONGO__URL: {{ .Values.core.secrets.MONGO_URL | b64enc }}
  {{- end }}
  {{- if .Values.core.secrets.SENDGRID_API }}
  SENDGRID__API: {{ .Values.core.secrets.SENDGRID_API | b64enc }}
  {{- end }}
  {{- if .Values.core.secrets.JWTTOKEN }}
  JWTTOKEN: {{ .Values.core.secrets.JWTTOKEN | b64enc }}
  {{- else }}
  JWTTOKEN: {{ uuidv4 | b64enc }}
  {{- end }}
  {{- if .Values.core.auth.clientId }}
  CLIENT_ID: {{ .Values.core.auth.clientId | b64enc }}
  {{- end }}
  {{- if .Values.core.auth.clientSecret }}
  CLIENT_SECRET: {{ .Values.core.auth.clientSecret | b64enc }}
  {{- end }}
  {{- if .Values.core.config.s3.enabled }}
  COS__apiKeyId: {{ .Values.core.config.s3.apiKeyId | b64enc }}
  COS__endpoint: {{ .Values.core.config.s3.endpoint | b64enc }}
  COS__serviceInstanceId: {{ .Values.core.config.s3.serviceInstanceId | b64enc }}
  COS__signatureVersion: {{ .Values.core.config.s3.signatureVersion | b64enc }}
  {{- else if .Values.minio.createservice }}
  COS__accessKeyId: {{ .Values.minio.accessKey | b64enc }}
  COS__endpoint: {{ printf "http://%s-minio:9000" .Release.Name | b64enc }}
  COS__secretAccessKey: {{ .Values.minio.secretKey | b64enc }}
  {{- end }}
