apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.common.secrets.secretmapref }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version}}"
type: Opaque
data:
  {{- if .Values.common.secrets.SLACKHOOK }}
  SLACKHOOK: {{ .Values.common.secrets.SLACKHOOK | b64enc }}
  {{- end }}
  {{- if .Values.nats.auth.unencrypted_password }}
  NATS__PASSWORD: {{ .Values.nats.auth.unencrypted_password | b64enc }}
  {{- else if .Values.nats.auth.password }}
  NATS__PASSWORD: {{ .Values.nats.auth.password | b64enc }}
  {{- end }}
  {{- if .Values.nats.clusterAuth.password }}
  NATS__CLUSTERPASSWORD: {{ .Values.nats.clusterAuth.password | b64enc }}
  {{- end }}
  {{- if .Values.nats.auth.token }}
  NATS__TOKEN: {{ .Values.nats.auth.token | b64enc }}
  {{- end }}
  {{- if .Values.nats.clusterAuth.token }}
  NATS__CLUSTERTOKEN: {{ .Values.nats.clusterAuth.token | b64enc }}
  {{- end }}