kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.nodepy.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.nodepy.name }}
    tier: {{ .Values.nodepy.tier }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version}}"
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.nodepy.port }}
      targetPort: {{ .Values.common.config.targetPort }}
  selector:
    app: {{ .Values.nodepy.name }}
    tier: {{ .Values.nodepy.tier }}
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
