kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.operator.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.operator.name }}
    tier: {{ .Values.operator.tier }}
    version: {{ .Values.operator.version }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version}}"
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.operator.name }}
      tier: {{ .Values.operator.tier }}
  template:
    metadata:
      name: {{ .Values.operator.name }}
      labels:
        app: {{ .Values.operator.name }}
        tier: {{ .Values.operator.tier }}
    spec:
      containers:
        - name: {{ .Values.operator.name }}
          image: {{ .Values.operator.image }}:{{ .Values.operator.version }}
          envFrom:
            - configMapRef:
                name: {{ .Values.common.name }}-config
            - secretRef:
                name: {{ .Values.common.name }}-secrets
            - configMapRef:
                name: {{ .Values.operator.name }}-config
          resources: {}
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: false
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "15"]
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
