# This is a basic workflow to help you get started with Actions

name: "CI pyspark-3.1.2"

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the latest branch
  push:
    branches: [latest]
    paths:
      - "applications/diem-spark/**/*pyspark-3.1.2*"
  pull_request:
    branches: [latest]
    paths:
      - "applications/diem-spark/**/*pyspark-3.1.2*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    working-directory: applications/diem-spark

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Login to quay.io
        run: echo "${{secrets.DOCKER_QUAY}}" | docker login -u="diem+ibm_deploy_robot" --password-stdin quay.io

      - name: Build the Docker image
        run: docker build . --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') --file images/Dockerfile-pyspark-3.1.2 --tag quay.io/diem/pyspark:latest

      - name: Push the Docker image
        run: docker push quay.io/diem/pyspark:latest
        if: github.event_name == 'push' && github.ref == 'refs/heads/latest'
