# This is a basic workflow to help you get started with Actions

name: "CI mongoloader"

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the latest branch
  push:
    branches: [latest]
    paths:
      - "helm/chart/**"
  pull_request:
    branches: [latest]
    paths:
      - "helm/chart/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    working-directory: helm/chart

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: azure/setup-helm@v1

      - name: Install quay plugin
        run: |
          helm plugin install https://github.com/app-registry/quay-helmv3-plugin
          helm quay --help

      - name: Login to quay.io
        run: echo "${{secrets.helm_test}}" | helm quay login -u huineng+diem_robot --password-stdin quay.io quay.io/huineng/diem

      - name: Push the Docker image
        run: helm quay push quay.io/huineng
